### ISSUE TITLE
Create Arbiter Test

### ISSUE THREAD

**Issue by pynchmeister** [zapproject/pythia#16]

**Comment by Hakob23** [comment]
@pynchmeister, could you please assign my account to this ticket?

**Comment by pynchmeister** [comment]
Yes, no problem

**Comment by Hakob23** [comment]
Done except the last scenario arbitertest.ts -> Test: Should initiate subscription:
After signing the "initializeSubscription" contract, it is not possible to send an array as an argument to a function. Error - Invalid arrayify value.
