### ISSUE TITLE
requestId field

### ISSUE THREAD

**Issue by jpkim921** [zapproject/pythia#38]
# Summary

One of the fields in config.json is "requestId." A user would normally enter an integer from 1 to 5 (for now) which corresponds to the trading pair it would mine. Typically a miner would mine a request, but when there aren't any requests in queue, the miner would go fetch and mine the pair requestId is set too.

We took it out for the initial testnet launch because of a bug where the miners would get stuck when requestData is sent AND requestId is in the config.

# Files to start with
* ./config.json (+ ./local_conf/config<#>.json)
* ./config/config.go

# Definition of Done
* Miner(s) can launch with requestData as a set field in config.json.
* Miner(s) can mine and submit automatically without any requestData being submitted.

**Comment by acemasterjb** [comment]
This has been addressed, miners can now  tip with the `requestData` flag, the amount they want to tip is configured with the `requestTips`  flag, and the interval for which they would like to tip for is set with the `requestInterval` flag but it defaults to 5 mins.
